


<ContactGrid>:
	BoxLayout:
		size:root.size	
		orientation:"vertical"
		ActionBar:
			ActionView:
				ActionPrevious:
					title:"PyContacts"
				ActionButton:
					text:"Settings"
	
		ScrollView:
			size:self.size
			GridLayout:
			
				cols: 2
				spacing: 5
				padding: 5


				Button:
					text:"Button 1"
				Button:
					text:"Button 2"
				Button:
					text:"Button 3"
				Button:
					text:"Button 4"
				Button:
					text:"Button 5"
				Button:
					text:"Button 6"
			

